python ./scripts/annotate_kb_program_turbo_grail.py --dataset grail \
--dataset_split final_grailqa_train_data \
--save_dir llm_results_turbo_grail_10_shot \
--prompt_file manual_prompts_grail_10.txt \
--output_file final_grailqa_train_data \
--n_parallel_prompts 1 \
--max_generation_tokens 512 \
--temperature 0.4 \
--sampling_n 1 \
--n_processes 1 \
--n_shots 0 \
-v