python ./scripts/annotate_kb_program.py --dataset wikitq \
--dataset_split results/s-expr/4_valid_expansions \
--save_dir llm_results \
--prompt_file manual_prompts.txt \
--output_file 4_valid_expansions.json \
--n_parallel_prompts 1 \
--max_generation_tokens 512 \
--temperature 0.4 \
--sampling_n 1 \
--n_processes 1 \
--n_shots 0 \
-v